name: Run Pylint, Mypy, and unittests
on:
    push:
        paths:
            - '*.py'
jobs:
    run_tests:
        strategy:
            fail-fast: true
            matrix:
                runs-on: [ ubuntu-latest, windows-latest ]
                python-version: [ "3.6.x", "3.7.x" ]
        steps:
            - name: Checkout code from branch
              uses: actions/checkout@v1

            - name: Install Python ${{ matrix.python-version }}
              uses: actions/setup-python@v1
              with:
                  python-version: ${{ matrix.python-version }}
                  architecure: x64

            - name: Check cache for venv
              uses: actions/cache@v1
              id: venv-cache
              with:
                  path: venv
                  key: ${{ matrix.os }}-${{ matrix.python-version }}-venv

            - name: Create Python virtual environment
              if: steps.venv-cache.outputs.cache-hit != "true"
              run: python -m venv venv

            - name: Enter Python virtual environment
              run: source venv/bin/activate

            - name: Install dependencies
              if: steps.venv-cache.outputs.cache-hit != "true"
              run: |
                pip install -r requirements.txt
                pip install -r requirements-dev.txt

            - name: Run Pylint and Mypy
              run: ./scripts/run-lint.sh argparse_utils.py task.py

            - name: Run unittests
              run: ./scripts/run-tests.sh argparse_utils.py task.py
